/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-02-15 22:20:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\t <link rel=\"stylesheet\" media=\"all\" href=\"/styles/sk.css\" />\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/images/favicon.ico\">\n");
      out.write("\t<title>SKUNK Game</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("ola.....\n");
      out.print( request.getAttribute("result") );
      out.write("\n");
      out.write("####\n");
      out.write("<div id=\"container\">\n");
      out.write("\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\tChoose your SkinK\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t<form action=\"/SkunkGame\" method=\"get\">\n");
      out.write("\t\t<div class=\"box\">\n");
      out.write("\t\t\t\t<div id=\"skp1\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button name=\"skin\" value=\"skin1\"><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skp2\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button name=\"skin\" value=\"skin2\"><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skp3\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button name=\"skin\" value=\"skin3\"><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skp4\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button name=\"skin\" value=\"skin4\"><img src=\"images/boss_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skp5\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button name=\"skin\" value=\"skin5\"><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skp7\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button name=\"skin\" value=\"skin6\"><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skp7\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button name=\"skin\" value=\"skin7\"><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t<div class=\"box\">\n");
      out.write("\t\t\t<div id=\"sk_letter_1\" class=\"normal\">S</div>\n");
      out.write("\t\t\t<div id=\"sk_letter_2\" class=\"normal\">K</div>\n");
      out.write("\t\t\t<div id=\"sk_letter_3\" class=\"normal\">U</div>\n");
      out.write("\t\t\t<div id=\"sk_letter_4\" class=\"normal\">N</div>\n");
      out.write("\t\t\t<div id=\"sk_letter_5\" class=\"normal\">K</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"box\">\n");
      out.write("\t\t\t\t<div id=\"skin_play_1\" class=\"off\">\n");
      out.write("\t\t\t\t\t<button  onclick='seat()'><img src=\"images/skp_up_1.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skin_player_1\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button ><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skin_player_1\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button ><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skin_player_1\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button ><img src=\"images/boss_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"sskin_player_1\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button ><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skin_player_1\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button ><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"sskin_player_1\" class=\"skp\">\n");
      out.write("\t\t\t\t\t<button ><img src=\"images/sk_red_s.png\" alt=\"Submit Form\"></button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\tvar eventSource = null;\n");
      out.write("\tfunction seat() {\n");
      out.write("\t\tconsole.log(\"seating...\");\n");
      out.write("\t\t//source = new EventSource('http://skunkgame.herokuapp.com/SkunkGame',  {withCredentials: true});\n");
      out.write("\t\tsource = new EventSource('http://localhost:8080/SkunkGame?msg=xxx');\n");
      out.write("\t\t/*eventSource.onopen \t\t= function() {};\n");
      out.write("\t\teventSource.onmessage \t= function(message) {console.log(message.data)};\n");
      out.write("\t\teventSource.onerror\t \t= function(merr) {console.log(\"error...\" + merr)};*/\n");
      out.write("\t\tsource.addEventListener('message', function(e) {\n");
      out.write("\t\t\t  console.log(e.data);\n");
      out.write("\t\t\t}, false);\n");
      out.write("\n");
      out.write("\t\t\tsource.addEventListener('open', function(e) {\n");
      out.write("\t\t\t  // Connection was opened.\n");
      out.write("\t\t\t}, false);\n");
      out.write("\n");
      out.write("\t\t\tsource.addEventListener('error', function(e) {\n");
      out.write("\t\t\t  if (e.readyState == EventSource.CLOSED) {\n");
      out.write("\t\t\t    // Connection was closed.\n");
      out.write("\t\t\t  }\n");
      out.write("\t\t\t}, false);\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
