/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-04-10 07:48:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" href=\"/styles/sk.css\" />\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" href=\"/styles/dice.css\" />\n");
      out.write("<link rel=\"stylesheet\" media=\"all\" href=\"/styles/smoke.css\" />\n");
      out.write("<link rel=\"shortcut icon\" href=\"/images/favicon.ico\">\n");
      out.write("<title>SKUNK Game</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body onload=\"sseSkunkGame()\">\n");
      out.write("\n");
      out.write("\t<div id=\"container\">\n");
      out.write("\n");
      out.write("\t<div>Choose your Skin</div>\n");
      out.write("\t\t<div id=\"overlay\">\n");
      out.write("\t\t\t<div class=box>\n");
      out.write("\t\t\t\t<div id=\"cube1\" class=\"cube1\">\n");
      out.write("\t\t\t\t\t<div class=\"cube1_face cube1_face_front\"><img src=\"/images/seis.png\"></div>\n");
      out.write("\t\t\t\t\t<div id=\"cube1_boss\" class=\"cube1_face cube1_face_back default\"><img src=\"/images/dot.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube1_face cube1_face_right\"><img src=\"/images/cinco.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube1_face cube1_face_left\"><img src=\"/images/dois.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube1_face cube1_face_top\"><img src=\"/images/treis.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube1_face cube1_face_bottom\"><img src=\"/images/quatro.png\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"cube2\" class=\"cube2\">\n");
      out.write("\t\t\t\t\t<div class=\"cube2_face cube2_face_front\"><img src=\"/images/seis.png\"></div>\n");
      out.write("\t\t\t\t\t<div id=\"cube2_boss\" class=\"cube2_face cube2_face_back default\"><img src=\"/images/dot.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube2_face cube2_face_right\"><img src=\"/images/cinco.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube2_face cube2_face_left\"><img src=\"/images/dois.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube2_face cube2_face_top\"><img src=\"/images/treis.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube2_face cube2_face_bottom\"><img src=\"/images/quatro.png\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"cube3\" class=\"cube3\">\n");
      out.write("\t\t\t\t\t<div class=\"cube3_face cube3_face_front\"><img src=\"/images/seis.png\"></div>\n");
      out.write("\t\t\t\t\t<div id=\"cube3_boss\" class=\"cube3_face cube3_face_back default\"><img src=\"/images/dot.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube3_face cube3_face_right\"><img src=\"/images/cinco.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube3_face cube3_face_left\"><img src=\"/images/dois.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube3_face cube3_face_top\"><img src=\"/images/treis.png\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"cube3_face cube3_face_bottom\"><img src=\"/images/quatro.png\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"box\">\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk1_choose\" class=\"on\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk1', 'choose')\">\n");
      out.write("\t\t\t\t\t<img id=\"img_choose\" src=\"images/skunk1_choose.png\" alt=\"Skunk 1\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk2_choose\" class=\"on\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk2', 'choose')\">\n");
      out.write("\t\t\t\t\t<img lass=\"img_choose\" src=\"images/skunk2_choose.png\" alt=\"Skunk 1\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk3_choose\" class=\"on\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk3', 'choose')\">\n");
      out.write("\t\t\t\t\t<img id=\"img_choose\" src=\"images/skunk3_choose.png\" alt=\"Skunk 1\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk4_choose\" class=\"on\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk4', 'choose')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/boss_s.png\" alt=\"Skunk 1\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk5_choose\" class=\"on\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk5', 'choose')\">\n");
      out.write("\t\t\t\t\t<img lass=\"img_choose\" src=\"images/skunk5_choose.png\" alt=\"Skunk 1\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk6_choose\" class=\"on\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk6', 'choose')\">\n");
      out.write("\t\t\t\t\t<img lass=\"img_choose\" src=\"images/skunk6_choose.png\" alt=\"Skunk 1\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk7_choose\" class=\"on\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk7', 'choose')\">\n");
      out.write("\t\t\t\t\t<img lass=\"img_choose\" src=\"images/skunk7_choose.png\" alt=\"Skunk 7\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<section>\n");
      out.write("\t\t\t\t<video id=\"skunk_smoke\" src=\"images/smoke1.mp4\" type=\"video/mp4\" muted class=\"\"></video>\n");
      out.write("\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t<span id=\"letter1\" onclick=\"smokeLetter('letter1')\" data_start=\"0\" data_stop=\".5\">S</span>\n");
      out.write("\t\t\t\t\t<span id=\"letter2\" onclick=\"smokeLetter('letter2')\" data_start=\"1.2\" data_stop=\"1.20001\">K</span>\n");
      out.write("\t\t\t\t\t<span id=\"letter3\" onclick=\"smokeLetter('letter3')\" data_start=\"2.1\" data_stop=\"2.1\">U</span>\n");
      out.write("\t\t\t\t\t<span id=\"letter4\" onclick=\"smokeLetter('letter4')\" data_start=\"3\" data_stop=\"3\">N</span>\n");
      out.write("\t\t\t\t\t<span id=\"letter5\" onclick=\"smokeLetter('letter5')\" data_start=\"4\" data_stop=\"4\">K</span>\n");
      out.write("\t\t\t\t</h1>\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\t\t<div class=\"box\">\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk1_play\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk1', 'down')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/dot.png\" alt=\"skunk 1\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk2_play\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk2', 'down')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/dot.png\" alt=\"skunk 2\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk3_play\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk3', 'down')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/dot.png\" alt=\"skunk 3\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk4_play\" class=\"off\">\n");
      out.write("\t\t\t\t\t<img src=\"images/dot.png\" alt=\"skunk 4\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk5_play\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk5', 'down')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/dot.png\" alt=\"skunk 5\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk6_play\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk6', 'down')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/dot.png\" alt=\"skunk 6\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"skunk7_play\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk7', 'down')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/dot.png\" alt=\"skunk 7\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"box\">\n");
      out.write("\t\t\t<div id=\"skunk1_score\">\n");
      out.write("\t\t\t\t<div id=\"skunk1_score_ride\" class=\"box on\">\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skunk1_score_total\" class=\"score_total on\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"skunk2_score\">\n");
      out.write("\t\t\t\t<div id=\"skunk2_score_ride\" class=\"box on\">\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skunk2_score_total\" class=\"score_total on\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"skunk3_score\">\n");
      out.write("\t\t\t\t<div id=\"skunk3_score_ride\" class=\"box on\">\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skunk3_score_total\" class=\"score_total on\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<button id=\"play_finish\" class=\"off\"\n");
      out.write("\t\t\t\t\t\tonclick=\"\">\n");
      out.write("\t\t\t\t\t\t<img src=\"images/dot.png\" alt=\"Play - Finish\">\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"skunk5_score\">\n");
      out.write("\t\t\t\t<div id=\"skunk5_score_ride\" class=\"box on\">\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skunk5_score_total\" class=\"score_total on\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"skunk6_score\">\n");
      out.write("\t\t\t\t<div id=\"skunk6_score_ride\" class=\"box on\">\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skunk6_score_total\" class=\"score_total on\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"skunk7_score\">\n");
      out.write("\t\t\t\t<div id=\"skunk7_score_ride\" class=\"box on\">\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"score_ride\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"skunk7_score_total\" class=\"score_total on\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"dice1\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk4', 'roll1')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/1dado.png\" alt=\"skunk 4\" width=\"180px\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"dice2\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk4', 'roll2')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/2dados.png\" alt=\"skunk 4\" width=\"180px\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<button id=\"dice3\" class=\"off\"\n");
      out.write("\t\t\t\t\tonclick=\"skunkMove('skunk4', 'roll3')\">\n");
      out.write("\t\t\t\t\t<img src=\"images/3dados.png\" alt=\"skunk 4\" width=\"180px\">\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("<script src=\"/js/smoke.js\"></script>\n");
      out.write("<script>\n");
      out.write("\tvar eventSource = null;\n");
      out.write("\tvar clientInitialSkunkId = \"skunk0\";\n");
      out.write("\n");
      out.write("\tvar clientSkunkSseId = getCookie(\"skunkSseId\");\n");
      out.write("\tvar clientSkunkGameId = getCookie(\"skunkGameId\");\n");
      out.write("\tvar clientSkunkId = getCookie(\"skunkId\");\n");
      out.write("\tvar skunkCookie = \"skunkSseId=0&skunkId=\" + clientInitialSkunkId + \"&skunkGameId=0\";\n");
      out.write("\n");
      out.write("\tif ((clientSkunkSseId != null) && (clientSkunkSseId.length > 0)) {\n");
      out.write("\t\tif ((clientSkunkGameId != null) && (clientSkunkGameId.length > 0)) {\n");
      out.write("\t\t\tif ((clientSkunkId != null) && (clientSkunkId.length > 0)) {\n");
      out.write("\t\t\t\tskunkCookie = \"skunkSseId=\" + clientSkunkSseId\n");
      out.write("\t\t\t\t\t\t+ \"&skunkGameId=\" + clientSkunkGameId + \"&skunkId=\"\n");
      out.write("\t\t\t\t\t\t+ clientSkunkId;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\tconsole.log(\"skunkCookie = \" + skunkCookie);\n");
      out.write("\n");
      out.write("\tfunction sseSkunkGame() {\n");
      out.write("\t\tconsole.log(\"sseSkunkGame...\");\n");
      out.write("\t\tsmokeAll();\n");
      out.write("\t\tif (location.hostname === \"localhost\" || location.hostname === \"127.0.0.1\") {\n");
      out.write("\t\t\tsource = new EventSource('http://localhost:8080/SkunkGame?' + skunkCookie);\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tsource = new EventSource('http://skunkgame.herokuapp.com/SkunkGame?' + skunkCookie);\n");
      out.write("\t\t}\n");
      out.write("\t\t/*source.onopen \t= function() {};\n");
      out.write("\t\teventSource.onmessage \t= function(message) {console.log(message.data)};\n");
      out.write("\t\teventSource.onerror\t \t= function(merr) {console.log(\"error...\" + merr)};*/\n");
      out.write("\n");
      out.write("\t\tsource.addEventListener('message', function(e) {\n");
      out.write("\t\t\tvar data = e.data.split('\\n').join('');\n");
      out.write("\t\t\tconsole.log(\"message= \" + data);\n");
      out.write("\t\t\teval(data);\n");
      out.write("\t\t}, false);\n");
      out.write("\n");
      out.write("\t\tsource.addEventListener('skunkSseId', function(e) {\n");
      out.write("\t\t\tconsole.log(\"skunkSseId= \" + e.data);\n");
      out.write("\t\t\tsetCookie(\"skunkSseId\", e.data, 1);\n");
      out.write("\t\t}, false);\n");
      out.write("\n");
      out.write("\t\tsource.addEventListener('skunkGameId', function(e) {\n");
      out.write("\t\t\tconsole.log(\"skunkGameId= \" + e.data);\n");
      out.write("\t\t\tsetCookie(\"skunkGameId\", e.data, 1);\n");
      out.write("\t\t}, false);\n");
      out.write("\n");
      out.write("\t\tsource.addEventListener('skunkId', function(e) {\n");
      out.write("\t\t\tconsole.log(\"skunkId= \" + e.data);\n");
      out.write("\t\t\tsetCookie(\"skunkId\", e.data, 1);\n");
      out.write("\t\t}, false);\n");
      out.write("\n");
      out.write("\t\tsource.addEventListener('open', function(e) {\n");
      out.write("\t\t\t// Connection was opened.\n");
      out.write("\t\t}, false);\n");
      out.write("\n");
      out.write("\t\tsource.addEventListener('error', function(e) {\n");
      out.write("\t\t\tif (e.readyState == EventSource.CLOSED) {\n");
      out.write("\t\t\t\t// Connection was closed.\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}, false);\n");
      out.write("\t}\n");
      out.write("\tfunction skunkMove(skunkId, skunkAction) {\n");
      out.write("\t\t// if different no move allowed\n");
      out.write("\t\tconsole.log(\"compara skunkId=\" + skunkId + \" com o do cookie=\"\n");
      out.write("\t\t\t\t+ getCookie(\"skunkId\"));\n");
      out.write("\t\tif ((skunkId == getCookie(\"skunkId\") || ((getCookie(\"skunkId\") == clientInitialSkunkId) && (skunkAction == \"choose\")))) {\n");
      out.write("\t\t\tconsole.log(\"vai sse..parms:skunkSseId=\" + getCookie(\"skunkSseId\")\n");
      out.write("\t\t\t\t\t+ \"&skunkGameId=\" + getCookie(\"skunkGameId\") + \"&skunkId=\"\n");
      out.write("\t\t\t\t\t+ skunkId + \"&skunkAction=\" + skunkAction);\n");
      out.write("\t\t\tvar request = new XMLHttpRequest();\n");
      out.write("\n");
      out.write("\t\t\trequest.open(\"GET\", \"/SkunkGame?skunkSseId=\"\n");
      out.write("\t\t\t\t\t+ getCookie(\"skunkSseId\") + \"&skunkGameId=\"\n");
      out.write("\t\t\t\t\t+ getCookie(\"skunkGameId\") + \"&skunkId=\" + skunkId\n");
      out.write("\t\t\t\t\t+ \"&skunkAction=\" + skunkAction, true);\n");
      out.write("\t\t\trequest.setRequestHeader('X-Requested-With', 'XMLHttpRequest');\n");
      out.write("\t\t\trequest.send(null);\n");
      out.write("\t\t\tconsole.log(\"foi sse...???\");\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\tfunction getCookie(cname) {\n");
      out.write("\t\tvar name = cname + \"=\";\n");
      out.write("\t\tvar decodedCookie = decodeURIComponent(document.cookie);\n");
      out.write("\t\tvar ca = decodedCookie.split(';');\n");
      out.write("\t\tfor (var i = 0; i < ca.length; i++) {\n");
      out.write("\t\t\tvar c = ca[i];\n");
      out.write("\t\t\twhile (c.charAt(0) == ' ') {\n");
      out.write("\t\t\t\tc = c.substring(1);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (c.indexOf(name) == 0) {\n");
      out.write("\t\t\t\treturn c.substring(name.length, c.length);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\treturn \"\";\n");
      out.write("\t}\n");
      out.write("\tfunction setCookie(cname, cvalue, exdays) {\n");
      out.write("\t\tvar d = new Date();\n");
      out.write("\t\td.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));\n");
      out.write("\t\tvar expires = \"expires=\" + d.toUTCString();\n");
      out.write("\t\tdocument.cookie = cname + \"=\" + cvalue + \";\" + expires + \";path=/\";\n");
      out.write("\t}\n");
      out.write("\tfunction removeCookies() {\n");
      out.write("\t\tvar res = document.cookie;\n");
      out.write("\t\tvar multiple = res.split(\";\");\n");
      out.write("\t\tfor (var i = 0; i < multiple.length; i++) {\n");
      out.write("\t\t\tvar key = multiple[i].split(\"=\");\n");
      out.write("\t\t\tdocument.cookie = key[0]\n");
      out.write("\t\t\t\t\t+ \" =; expires = Thu, 01 Jan 1970 00:00:00 UTC\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
